---
- name: Install k9s on CentOS 7
  hosts: master
  become: yes

  tasks:
    - name: Install required dependencies
      yum:
        name:
          - epel-release
          - wget
          - tar
        state: present

    - name: Get latest k9s version
      shell: |
        curl -s https://api.github.com/repos/derailed/k9s/releases/latest | \
        grep tag_name | cut -d '"' -f 4 | sed 's/v//'
      register: k9s_version
      changed_when: false

    - name: Download k9s binary
      get_url:
        url: "https://github.com/derailed/k9s/releases/download/v{{ k9s_version.stdout }}/k9s_Linux_amd64.tar.gz"
        dest: "/tmp/k9s_Linux_amd64.tar.gz"

    - name: Extract k9s binary
      unarchive:
        src: "/tmp/k9s_Linux_amd64.tar.gz"
        dest: "/tmp/"
        remote_src: yes

    - name: Move k9s binary to /usr/local/bin
      command: mv /tmp/k9s /usr/local/bin/k9s
      args:
        creates: /usr/local/bin/k9s

    - name: Ensure k9s is executable
      file:
        path: /usr/local/bin/k9s
        mode: '0755'

    - name: Verify k9s installation
      command: k9s version
      register: k9s_check
      changed_when: false

    - debug:
        msg: "k9s installed successfully! Version: {{ k9s_check.stdout }}"

    - name: Clean up downloaded files
      file:
        path: "/tmp/k9s_Linux_amd64.tar.gz"
        state: absent
